
// This file holds the data for the product lists to keep the main components clean.

export const verticalPacks: string[] = [
  "40 GIỌT THỦY TINH ĐỘT BIẾN",
  "50 BỌ CẠP",
  "50 CÁNH TAY ROBOT",
  "50 HỔ PHÁCH",
  "50 RỒNG CƠ KHÍ",
  "50 THANG VÔ ĐỊNH",
  "50 THÀNH PHỐ LỘN NGƯỢỢC",
  "50+ SÂU VŨ TRỤ",
  "50+ XƯƠNG LỒNG NGỰC",
  "60 TƯỢNG ĐÁ",
  "100 CỔNG LÂU ĐÀI MA",
  "100 LINH HỒN SÓI",
  "100 MẮT VŨ TRỤ",
  "120+ CƠN BÃO MA ÁM",
  "120+ MẶT NẠ KỊCH CỠ",
  "130+ BÁNH RĂNG CƠ KHÍ",
  "130+ QUÁI VẬT MỰC",
  "140+ CÁ MẬP ROBOT",
  "140+ CÔN TRÙNG CƠ KHÍ",
  "140+ DƠI CƠ KHÍ",
  "180+ LÕI NĂNG LƯỢNG",
];

export const widescreenPacks: string[] = [
  "50 KIM CƯƠNG",
  "70 CHÓ 3 ĐẦU NEON",
  "70 NGÃI VÀNG",
  "100 CỔNG LÂU ĐÀI MA",
  "100 ĐẦU QUỶ MEDUSA",
  "100 HỘP SỌ PHA LÊ",
  "100 KHỐI LẬP PHƯƠNG VÔ CỰC",
  "100 MANG NHỆN LAZE",
  "100 MOTO MA",
  "100 NHÀ MÁY HỖN LOẠN",
  "100 RẮN ROBOT",
  "100 SÓNG ÂM BẠO LỰC",
  "100 VŨ KHÍ CYBERPUNK",
  "100 VŨ NỮ THIÊN HÀ",
  "100 VƯỢT QUỶ",
  "120 ĐOÀN TÀU MA",
  "140 CỘT SỐNG",
  "150 CÁNH CỔNG ĐỊA NGỤC",
  "150 QUÁI VẬT ĐIỆN TỬ",
  "150 TÀU CHIẾN KHÔNG GIAN",
  "MÊ CUNG LAZE",
];
